name: deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-gitops-demo
  RESOURCE_GROUP_LOCATION: "uksouth"
  ACR_NAME: "colinbealesacr"
  CLUSTER_NAME: clu-gitops
  CLUSTER_DNS: colindns

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.RESOURCE_GROUP_LOCATION}}
            echo "Azure resource group created"

      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: rg-gitops-demo
          template: ./IaC/arm/azuredeployacr.json
          parameters: acrName=${{env.ACR_NAME}}

      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: rg-gitops-demo
          template: ./IaC/arm/azuredeployaks.json
          parameters: aksClusterName=${{env.CLUSTER_NAME}}
            dnsPrefix=${{env.CLUSTER_DNS}}
            agentCount=1

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az aks update -n ${{env.CLUSTER_NAME}} -g ${{env.RESOURCE_GROUP}} --attach-acr ${{env.ACR_NAME}}
            echo "Attached ACR to AKS"

      - uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
